# Generated by Django 3.0.5 on 2020-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_auto_20200414_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(max_length=20),
        ),
    ]
