# Generated by Django 3.0.5 on 2020-04-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_auto_20200414_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=4),
        ),
    ]
