# Generated by Django 3.0.5 on 2020-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_auto_20200414_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defensive_rebounds_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='offensive_rebounds_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
