# Generated by Django 3.0.5 on 2020-04-17 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_auto_20200417_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('home_team', models.IntegerField()),
                ('away_team', models.IntegerField()),
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('winning_team_id', models.IntegerField()),
                ('losing_team_id', models.IntegerField()),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('top_scorer_home', models.IntegerField()),
                ('top_scorer_away', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=None, null=True)),
                ('json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.date.today)),
                ('opponent', models.CharField(max_length=4)),
                ('win_loss', models.CharField(max_length=1)),
                ('minutes', models.IntegerField(default=0)),
                ('field_goals_made', models.IntegerField(default=0)),
                ('field_goals_attempted', models.IntegerField(default=0)),
                ('three_point_made', models.IntegerField(default=0)),
                ('three_point_attempted', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('personal_fouls', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Player')),
            ],
        ),
    ]
