# Generated by Django 3.0.5 on 2020-04-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0008_game_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_name',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_name',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
    ]
