# Generated by Django 3.0.5 on 2020-04-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0009_auto_20200417_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_name',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='winner_name',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
    ]
