# Generated by Django 3.0.5 on 2020-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0010_auto_20200417_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='json',
            new_name='data',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_record',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_record',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
