# Generated by Django 3.0.5 on 2020-04-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_auto_20200418_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_score_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_score_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
