# Generated by Django 3.0.5 on 2020-04-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0012_auto_20200418_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_team_score_points',
            new_name='top_scorer_away_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_team_score_points',
            new_name='top_scorer_home_points',
        ),
    ]
