# Generated by Django 3.0.5 on 2020-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0013_auto_20200418_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='def_rebounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='off_rebounds',
            field=models.IntegerField(default=0),
        ),
    ]
