# Generated by Django 3.0.5 on 2020-04-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0014_auto_20200418_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='player_id',
            new_name='player',
        ),
    ]
