# Generated by Django 3.0.5 on 2020-04-19 07:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0015_auto_20200418_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('team_abv', models.CharField(max_length=5)),
                ('team_wins', models.IntegerField()),
                ('team_loses', models.IntegerField()),
                ('conference', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('conference_rank', models.CharField(max_length=2)),
                ('points_total', models.IntegerField()),
                ('assists_total', models.IntegerField()),
                ('offensive_rebounds_total', models.IntegerField()),
                ('defensive_rebounds_total', models.IntegerField()),
                ('rebounds_total', models.IntegerField()),
                ('blocks_total', models.IntegerField()),
                ('steals_total', models.IntegerField()),
                ('turnovers_total', models.IntegerField()),
                ('personal_fouls_total', models.IntegerField()),
                ('free_throws_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('three_point_made', models.IntegerField()),
                ('three_point_attempted', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('players', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
