# Generated by Django 3.0.5 on 2020-04-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0016_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
