# Generated by Django 3.0.5 on 2020-04-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0017_auto_20200419_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_loses',
            new_name='team_losses',
        ),
    ]
