# Generated by Django 3.0.5 on 2020-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0018_auto_20200419_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_win_percentage_start',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_win_percentage_start',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
