# Generated by Django 3.0.5 on 2020-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0019_auto_20200421_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='away_losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='away_wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='home_losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='home_wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
