# Generated by Django 3.0.5 on 2020-04-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0022_team_opponent_points_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='divisional_losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='divisional_wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
