# Generated by Django 3.0.5 on 2020-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0023_auto_20200423_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_win_percentage_start',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_win_percentage_start',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
