# Generated by Django 3.0.5 on 2020-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0024_auto_20200427_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
