# Generated by Django 3.0.5 on 2020-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0025_player_is_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_injuried',
            field=models.BooleanField(default=False),
        ),
    ]
