# Generated by Django 3.0.5 on 2020-04-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0026_player_is_injuried'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_injuried',
            new_name='is_injured',
        ),
    ]
