# Generated by Django 3.0.5 on 2020-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0028_auto_20200503_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
