# Generated by Django 3.0.5 on 2020-05-04 04:45

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0029_game_is_simulated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePreview',
            fields=[
                ('game_date', models.DateField(default=datetime.date.today)),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('higher_seeding_id', models.IntegerField()),
                ('lower_seeding_id', models.IntegerField()),
                ('higher_seeding_name', models.CharField(max_length=35)),
                ('lower_seeding_name', models.CharField(max_length=35)),
                ('home_team_name', models.CharField(max_length=35)),
                ('away_team_name', models.CharField(max_length=35)),
                ('game_preview_id', models.IntegerField(primary_key=True, serialize=False)),
                ('votes_home_team', models.IntegerField(default=0)),
                ('votes_home_away', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MVPPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_higher_seed', models.IntegerField(default=0)),
                ('votes_lower_seed', models.IntegerField(default=0)),
                ('higher_seed_id', models.IntegerField()),
                ('lower_seed_id', models.IntegerField()),
                ('higher_seed_name', models.CharField(max_length=35)),
                ('lower_seed_name', models.CharField(max_length=35)),
                ('higher_seed_wins', models.IntegerField(default=0)),
                ('lower_seed_wins', models.IntegerField(default=0)),
                ('higher_seed_loses', models.IntegerField(default=0)),
                ('lower_seed_loses', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('playoff_type', models.CharField(max_length=35)),
                ('game_ids', jsonfield.fields.JSONField()),
            ],
        ),
    ]
