# Generated by Django 3.0.5 on 2020-05-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0030_gamepreview_mvppoll_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=40)),
                ('team_abv', models.CharField(max_length=4)),
                ('votes', models.IntegerField(default=0)),
                ('points_pg', models.IntegerField(default=0)),
            ],
        ),
    ]
