# Generated by Django 3.0.5 on 2020-05-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0031_mvpvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
