# Generated by Django 3.0.5 on 2020-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0032_auto_20200506_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='id',
        ),
        migrations.AddField(
            model_name='serie',
            name='series_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
