# Generated by Django 3.0.5 on 2020-05-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0033_auto_20200506_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepreview',
            name='series_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basketball.Serie'),
            preserve_default=False,
        ),
    ]
