# Generated by Django 3.0.5 on 2020-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0034_gamepreview_series_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
