# Generated by Django 3.0.5 on 2020-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0035_serie_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='higher_seed_abv',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='serie',
            name='lower_seed_abv',
            field=models.CharField(default='', max_length=4),
        ),
    ]
