# Generated by Django 3.0.5 on 2020-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0036_auto_20200506_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepreview',
            name='is_necessary',
            field=models.BooleanField(default=True),
        ),
    ]
