# Generated by Django 3.0.6 on 2020-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0039_gamepreview_game_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countVisitors', models.IntegerField(default=0)),
            ],
        ),
    ]
